// =====================================================================
// GITHUB SCANNER PRO MODULE 3.0 (LIVE REST API)
// =====================================================================

const GH_PRO = {
  MAX_FILES: 1000,      // max files per scan (browser-safe)
  CONCURRENCY: 6,       // parallel fetch pool
  API: "https://api.github.com/repos/",
  TOKEN: ""             // optional GitHub token
};

// =====================================================================
// PARSE REPO URL
// =====================================================================

function parseRepoURL(url) {
  const m = url.match(/github\.com\/([^\/]+)\/([^\/#?]+)/i);
  if (!m) return null;
  return { owner: m[1], repo: m[2].replace(".git","") };
}

// =====================================================================
// FETCH REPO TREE (REST API, recursive)
// =====================================================================

async function ghFetchTree(owner, repo) {
  const repoInfo = await fetch(`${GH_PRO.API}${owner}/${repo}`, {
    headers: GH_PRO.TOKEN ? { Authorization: `token ${GH_PRO.TOKEN}` } : {}
  }).then(r => r.json());

  const branch = repoInfo.default_branch;

  const url = `${GH_PRO.API}${owner}/${repo}/git/trees/${branch}?recursive=1`;
  const r = await fetch(url, {
    headers: GH_PRO.TOKEN ? { Authorization: `token ${GH_PRO.TOKEN}` } : {}
  });

  const data = await r.json();
  if (!data.tree) throw new Error("Repo tree fetch failed");

  return data.tree
    .filter(f => f.type === "blob")
    .slice(0, GH_PRO.MAX_FILES);
}

// =====================================================================
// PARALLEL FILE SCANNER
// =====================================================================

async function ghScanFiles(files, owner, repo, bar, text) {
  let results = [];
  let done = 0;

  async function worker(file) {
    const raw = `https://raw.githubusercontent.com/${owner}/${repo}/HEAD/${file.path}`;
    try {
      const content = await fetch(raw).then(r => r.text());
      const score = ghAIHeuristic(content);
      const lang = ghDetectLanguage(file.path);
      results.push({ name: file.path, ai: score, language: lang, size: content.length });
    } catch(e) {
      console.warn("Fetch failed:", file.path, e);
    }

    done++;
    const pct = Math.floor((done / files.length) * 100);
    bar.style.width = pct + "%";
    text.textContent = `Scanning ${done}/${files.length} files`;
  }

  const pool = [];
  for (const f of files) {
    const p = worker(f).then(() => pool.splice(pool.indexOf(p), 1));
    pool.push(p);
    if (pool.length >= GH_PRO.CONCURRENCY) await Promise.race(pool);
  }

  await Promise.all(pool);
  return results;
}

// =====================================================================
// AI HEURISTIC
// =====================================================================

function ghAIHeuristic(code) {
  let score = 0;
  const rules = [
    /as an ai language model/i,
    /generated by chatgpt/i,
    /auto-generated/i,
    /example usage/i,
    /lorem ipsum/i,
    /todo:/i,
    /mock data/i
  ];
  rules.forEach(r => { if(r.test(code)) score += 15; });

  if (code.match(/function\s+[^{]+{[\s\S]{300,}}/g)) score += 10;
  if (/(.)\1{8,}/g.test(code)) score += 10;

  const commentRatio = (code.match(/\/\/|#/g) || []).length / Math.max(code.split("\n").length, 1);
  if (commentRatio > 0.3) score += 10;
  if (code.match(/(.{20,})\1{2,}/gs)) score += 15;
  if (code.length > 8000) score += 5;

  return Math.min(score, 100);
}

// =====================================================================
// LANGUAGE DETECTION (by file extension)
// =====================================================================

function ghDetectLanguage(path) {
  const ext = path.split('.').pop().toLowerCase();
  if(["ts"].includes(ext)) return "TypeScript";
  if(["js"].includes(ext)) return "JavaScript";
  if(["py"].includes(ext)) return "Python";
  if(["java"].includes(ext)) return "Java";
  if(["c"].includes(ext)) return "C";
  if(["cpp"].includes(ext)) return "C++";
  if(["cs"].includes(ext)) return "C#";
  if(["go"].includes(ext)) return "Go";
  if(["html"].includes(ext)) return "HTML";
  if(["css"].includes(ext)) return "CSS";
  if(["php"].includes(ext)) return "PHP";
  if(["rb"].includes(ext)) return "Ruby";
  return "Other";
}

// =====================================================================
// UPDATE REPO STATS (matches HTML structure)
// =====================================================================

function updateRepoStats(files) {
  const totalFiles = files.length;
  const avgAI = totalFiles > 0 ? Math.round(files.reduce((a, f) => a + f.ai, 0) / totalFiles) : 0;
  const aiFiles = files.filter(f => f.ai >= 60).length;
  const humanFiles = files.filter(f => f.ai < 40).length;
  const mixedFiles = files.filter(f => f.ai >= 40 && f.ai < 60).length;

  document.getElementById("gh-files").textContent = totalFiles;
  document.getElementById("gh-avg").textContent = avgAI + "%";
  document.getElementById("gh-aif").textContent = aiFiles;
  document.getElementById("gh-hf").textContent = humanFiles;
}

// =====================================================================
// RENDER RESULTS (AI %, heatmap, language)
// =====================================================================

function renderGHResults(owner, repo, files) {
  const avgAI = files.length > 0 ? Math.round(files.reduce((a, f) => a + f.ai, 0) / files.length) : 0;
  const aiFiles = files.filter(f => f.ai >= 60).length;
  const humanFiles = files.filter(f => f.ai < 40).length;
  const mixedFiles = files.filter(f => f.ai >= 40 && f.ai < 60).length;

  // Update repo stats in the metric grid
  updateRepoStats(files);

  const res = document.getElementById("gh-results");
  res.innerHTML = `
  <div class="repo-card" style="margin-top:20px; border-top:1px solid var(--border); padding-top:20px;">
    <div class="repo-name" style="font-weight:800; margin-bottom:15px; font-size:16px;">🐙 ${owner}/${repo}</div>
    <div class="repo-meta" style="display:flex; gap:20px; margin-bottom:15px; font-family:var(--mono); font-size:12px; color:var(--text-muted);">
      <span>📁 ${files.length} files scanned</span>
      <!-- Bagian AI average dihapus -->
      <span>🧠 AI files ${aiFiles}</span>
      <span>👨‍💻 Human files ${humanFiles}</span>
      <span>⚖️ Mixed ${mixedFiles}</span>
    </div>
    <div class="file-list" style="max-height:400px; overflow-y:auto;">
      ${files.map(f => {
        const col = f.ai >= 60 ? "#ff4d4d" : f.ai >= 40 ? "#ffc107" : "#2ecc71";
        const label = f.ai >= 60 ? "AI" : f.ai >= 40 ? "MIXED" : "Human";
        return `
        <div class="file-item" style="display:grid; grid-template-columns:minmax(200px,1fr) 80px 80px 60px 60px; gap:10px; align-items:center; padding:8px 0; border-bottom:1px solid var(--border); font-size:12px;">
          <span class="file-name" style="font-family:var(--mono); color:var(--text); white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">${f.name}</span>
          <span class="file-lang" style="color:var(--text-muted);">${f.language}</span>
          <div class="file-bar-wrap" style="background:var(--surface); height:16px; border-radius:8px; overflow:hidden; width:80px;">
            <div class="file-bar" style="height:100%; width:${f.ai}%; background:${col};"></div>
          </div>
          <span class="file-pct" style="font-family:var(--mono);">${f.ai}%</span>
          <span class="file-badge" style="font-size:9px; padding:2px 6px; border-radius:20px; background:${col}20; color:${col};">${label}</span>
        </div>`;
      }).join("")}
    </div>
  </div>`;
}

// =====================================================================
// MAIN SCAN ENTRY
// =====================================================================

async function ghScanReal() {
  const url = document.getElementById("gh-url").value.trim();
  const parsed = parseRepoURL(url);
  if (!parsed) { alert("Invalid GitHub repo URL"); return; }

  const { owner, repo } = parsed;
  const overlay = document.getElementById("gh-overlay");
  const bar = document.getElementById("gh-progress-bar");
  const text = document.getElementById("gh-spin-text");

  overlay.style.display = "flex";
  bar.style.width = "0%";
  text.textContent = "Fetching repo files...";

  try {
    const files = await ghFetchTree(owner, repo);
    text.textContent = `Found ${files.length} files`;
    const results = await ghScanFiles(files, owner, repo, bar, text);
    overlay.style.display = "none";
    renderGHResults(owner, repo, results);
  } catch (e) {
    overlay.style.display = "none";
    alert("Scan error: " + e.message);
  }
}

// =====================================================================
// INITIALIZE DEFAULT VALUES
// =====================================================================

// Set initial placeholder values
document.addEventListener('DOMContentLoaded', function() {
  document.getElementById("gh-files").textContent = "—";
  document.getElementById("gh-avg").textContent = "—";
  document.getElementById("gh-aif").textContent = "—";
  document.getElementById("gh-hf").textContent = "—";
});